### ISSUE TITLE
Dynamically setting additional properties on route change

### ISSUE THREAD

**Issue by lukahartwig** [gtm-support/vue-gtm#110]
## Request / Idea

Allow `meta.gtmAdditionalEventData` to be dynamically resolved whenever `router.afterEach` is called. This could be done for example by allowing `gtmAdditionalEventData` to be a function or by adding a callback to the options that is called to resolve `gtmAdditionalEventData`.

## Additional Context

Currently additional properties  can be set on a per route basis with `meta.gtmAdditionalEventData`. I would like to read these properties from the vuex store when the route changes because the data changes over time.

**Comment by Shinigami92** [comment]
Sounds interesting. Are you interested to open a PR for this?
