### ISSUE TITLE
Bug: npm 7 peer vue dep

### ISSUE THREAD

**Issue by reslear** [gtm-support/vue-gtm#12]
<img width="519" alt="Screenshot 2021-05-17 at 18 55 54" src="https://user-images.githubusercontent.com/12596485/118519225-98d84680-b741-11eb-8b8b-303d345c9a28.png">

bug with install npm 7 without **--legacy-peer-deps**
peer vue@"^3.0.0" from @gtm-support/vue-gtm@1.0.0
for **vue 3.1.0-beta.3**

**Comment by Shinigami92** [comment]
Could you create a simple minimal reproduction repo that I can checkout/clone?
Maybe it's just changing the peer dependency from `^3.0.0` to `>=3.0.0 <4.0.0` :thinking:, but I'm not sure
Does it work with yarn or other tools? Does it work with npm 6?

**Comment by reslear** [comment]
> Could you create a simple minimal reproduction repo that I can checkout/clone?
> Maybe it's just changing the peer dependency from `^3.0.0` to `>=3.0.0 <4.0.0` 🤔, but I'm not sure
> Does it work with yarn or other tools? Does it work with npm 6?

npm 6 ok, this problem only in npm 7 maybe use `">=3.0.0 || ^3.0.0-beta"`

**Comment by Shinigami92** [comment]
So I checked via this site: https://jubianchi.github.io/semver-check/#/^3.0.0/3.1.0-beta.3
that the peer dependency is configured right and that `^3.0.0` also satisfies `3.1.0-beta.3`

So I don't what I need to do here :confused:

**Comment by reslear** [comment]
ok @Shinigami92 see please https://semver.npmjs.com/

you
<img width="661" alt="Screenshot 2021-05-25 at 18 59 33" src="https://user-images.githubusercontent.com/12596485/119530092-5b039f80-bd8b-11eb-92a8-956fe1fc1595.png">

and  my `^3 || ^3.0.0-alpha || ^3.1.0-alpha`
<img width="665" alt="Screenshot 2021-05-25 at 19 07 02" src="https://user-images.githubusercontent.com/12596485/119531301-7622df00-bd8c-11eb-9bcc-15361f8e364d.png">

**Comment by Shinigami92** [comment]
Okay we need to find a version range that includes everything between `>=3.* and <4` :thinking: 
I don't want to specify for every beta version a `3.X...-alpha`

So I don't want to maintain something like `^3 || ^3.0.0-alpha || ^3.1.0-alpha || ^3.2.0-alpha || 
^3.3.0-alpha || ^3.4.0-alpha` ... beyond to infinity ...

How do I do that?

**Comment by Shinigami92** [comment]
Beside that, I'm not sure if I "want" to support a beta version :thinking:  
I mean, yeah it works, but I will not deliver support if there is something broken based on a beta version
Just when it will release officially, I will update an fix the breaking

**Comment by reslear** [comment]
@Shinigami92 
1. Definitely due instead of `>=3.* and <4` use `^3`
2. Support only last beta releases `^3.1.0-alpha` It is unlikely that someone needs old beta, and about support - update lazily :)

<img width="376" alt="Screenshot 2021-05-25 at 19 55 39" src="https://user-images.githubusercontent.com/12596485/119537902-34e1fd80-bd93-11eb-89a7-d3ef82af6f6b.png">

final result: `^3 || ^3.1.0-alpha`

**Comment by Shinigami92** [comment]
Cause I cannot find a way to specify all beta versions with just one easy range, I'm sorry, but I think I will not support beta versions for now.

If you are using beta versions you are an early adopter and there can be errors with that.

Setting it explicitly in my `package.json` means I officially support these non-production ready versions.

Also it's not only `vue`, but also `vue-router` that could get a beta...

So I would currently need something like

```
vue: ^3.0.0-a || ^3.1.0-a || ^3.2.0-a ...
vue-router: ^4.0.0-a || ^4.1.0-a || ^4.2.0-a ...
```

Sorry, but I don't want to create a release just due to there is a new beta release :slightly_frowning_face:  

If I understand correctly using `--legacy-peer-deps` is the correct workaround for now, isn't it? That's cause you rely on a beta version.

**Comment by reslear** [comment]
ok, I agree
