### ISSUE TITLE
Scroll tracking on every view

### ISSUE THREAD

**Issue by Dreckr** [gtm-support/vue-gtm#16]
Hello, guys!

First of all, thanks for building this plugin!

I'm building a SPA using it and I've managed to track all page views correctly, but I've noticed that the "scroll" event is only fired once and this is due to gtag only tracking scroll once per page load. Since there are no full page loads after the first one on a SPA, scroll tracking doesn't work properly.

As a workaround, I've found this [GTM recipe](https://www.bounteous.com/insights/2017/09/27/scroll-tracking-recipe-gtm/) that basically includes tags that tracks scroll behavior and allows you to reset the scroll tracking every time the view changes.

It would be very nice to have all of this integrated into vue-gtm.

**Comment by Shinigami92** [comment]
In and of itself sounds nice, but in the article I read about GA and its `UA`-id  
This package tries to only use GTM without GA, so no `UA`-id is passed to this package

If you still think this is the right package, I would be really happy to review a PR from you :slightly_smiling_face:

**Comment by Shinigami92** [comment]
Closing for now as no response for nearly a year now

Feel free to reopen and open a PR for it
