### ISSUE TITLE
Accessing the gtm instance outsite of a component

### ISSUE THREAD

**Issue by sametsafak** [gtm-support/vue-gtm#174]
Hi,

In the docs, it says: `You can also access the instance anywhere whenever you imported Vue by using Vue.gtm. It is especially useful when you are in a store module or somewhere else than a component's scope.` 

But in vue 3, you can't use 
```javascript
import  Vue from 'vue'
```

How can I access gtm outside of a component? Could you give an example, especially what to import in a js file with Vue 3? I'm trying to access it in a separated js file (helper).

---
**Edit:** I guess I found It. First I need to export **app** from **main.js**, then import it into a js file to consume.

main.js:
```javascript
import { createApp } from 'vue'
import App from '@/App.vue'
...
const app = createApp(App)
...

// this is the key
export default app
```

helper.js:
```javascript
import app from '@/main'

console.log(app.config.globalProperties.$gtm)
```

If my way is correct, could you update the docs? 

Thank you!

**Comment by Shinigami92** [comment]
Are you searching for this? https://github.com/gtm-support/vue-gtm#using-with-composition-api

Your way is also a way to do it, but I think you can just use `useGtm` like e.g. any other composable.

**Comment by sametsafak** [comment]
Yes it seems way better. I updated my code. And I also figured out how can I access my app instance outside of my app :)

But the docs may need to be updated due to vue 3's import stuff as I mentioned above.

Thank you
