### ISSUE TITLE
Google Analytics 4 support?

### ISSUE THREAD

**Issue by alexander-schneider** [gtm-support/vue-gtm#183]
## Request / Idea

Is Google Analytics 4 supported yet? Any plans to do that? The old support runs out 1. Juli 2023

**Comment by Shinigami92** [comment]
This is for GTM = Google Tag Manager
I think there are other packages that handles GA = Google Analytics

That said, I only currently hold this package alive but will not adding any features from my side.
So just managing PRs via review and releasing if needed.
