### ISSUE TITLE
Whether the event name is definable

### ISSUE THREAD

**Issue by AllenYu0118** [gtm-support/vue-gtm#197]
## Request / Idea
I found that the event name is' Content-view 'and cannot be customized, would you consider supporting incoming?

**Comment by Shinigami92** [comment]
Feel free to draft a PR.
Could you please also describe what your use-case is and what this param/even does? I'm not used to GA but just took over this library for maintenance.

**Comment by AllenYu0118** [comment]
OK，I'll try

**Comment by Shinigami92** [comment]
@AllenYu0118 is your problem solved?
You closed the issue but I never get a PR or similar from you 🤔

**Comment by AllenYu0118** [comment]
Oh, my mistake. It turned off smoothly 🤪

**Comment by Shinigami92** [comment]
Released in https://github.com/gtm-support/vue-gtm/releases/tag/1.6.0
