### ISSUE TITLE
Filter internal traffic by IP address

### ISSUE THREAD

**Issue by Spasms** [gtm-support/vue-gtm#250]
I'm trying to filter our our internal traffic by IP address. I've setup the appropriate filters in Google Analytics data streams/settings.

It seems like the user's IP address is not being passed from GTM to GA4.

Has anyone experienced this or have any insights?

**Comment by Shinigami92** [comment]
You might want to ask this question again on StackOverflow 
I think there it's a much higher possibility to get an answer
