### ISSUE TITLE
Bug: Vue2 npm ERR! ERESOLVE could not resolve

### ISSUE THREAD

**Issue by thilinadinith** [gtm-support/vue-gtm#294]
tried to install the vue2 plugin and it gives so many errors as below
I'm using Vue 2.6.*

<img width="655" alt="image" src="https://user-images.githubusercontent.com/11405429/200509922-4c8b5f86-3809-465a-9757-8dadf9a7a833.png">

**Comment by Shinigami92** [comment]
Try to pin your version to `1.3.0`

**Comment by Shinigami92** [comment]
https://www.npmjs.com/package/@gtm-support/vue2-gtm/v/1.3.0
