### ISSUE TITLE
Bug: Can you please update to allow Google IDs to begin with G-

### ISSUE THREAD

**Issue by aonghas** [gtm-support/vue-gtm#356]
## Info

| Tool   | Version       |
| ------ | ------------- |
| Plugin | v2.0.0        |

## Input

```js

```

## Output or Error

```bash

'G-xxxxxxxxxx' is not a valid GTM-ID (/^GTM-[0-9A-Z]+$/). Did you mean 'GTM-xxxxxxxxxx'?
```

## Expected Output

```bash

```

**Comment by Shinigami92** [comment]
Please create a for for that, because the package is not designed to work with non GTM things
Alternatively: search for alternative packages
