### ISSUE TITLE
Bug: router can not be passed to the plugin because the corresponding property doesn't exist

### ISSUE THREAD

**Issue by itinance** [gtm-support/vue-gtm#412]
## Info

| Tool   | Version       |
| ------ | ------------- |
| Plugin | v2.2.0        |
| Vue    | v3.0.0        |
| Node   | v18.7.1        |
| OS     | mac |

## Input

```js
app.use(
  createGtm({
    id: 'GTM-xxxxxx', 
   vueRouter: router
 

```

## Output or Error

```bash
Property 'vouRouter' doesn't exist.
```

## Expected Output

```bash
// nothing
```

## Additional Context

The README states how to pass the `router` to the plugin. However, the mentioned property doesn't exists.
How to do that?

**Comment by Shinigami92** [comment]
its not `vouRouter` its `vueRouter`

**Comment by itinance** [comment]
i was to fast, sorry and thanks :)
The issue is another one: it complains that the passed router is not compatible to the expected router-type.
I use quasar framework v2, didn't expect that they use a router which is differently then the vue-router.
