### ISSUE TITLE
Problems wit Google consent mode v2

### ISSUE THREAD

**Issue by miikkalaitinen** [gtm-support/vue-gtm#414]
I might be that I am just incredibly stupid but how can i get consent mode v2 working with this package? 

I am quite new to Google analytics and tag manager and would need to add the new ad personalisation consent signals that are required for GA4 in the European Economic Area.

Or is this just the wrong tool for the job?

Any help is highly appreciated.

**Comment by Shinigami92** [comment]
@miikkalaitinen If you found a solution, it is good if you could provide some info, so others running into the same issue can get that info.

**Comment by miikkalaitinen** [comment]
I added a trigger that activates on our consent form agree button and hooked that up to a [Community Template](https://tagmanager.google.com/gallery/#/owners/gtm-templates-simo-ahava/templates/consent-mode). The setup worked but it took **well over a week** for google to detect that the new signals were online.
