### ISSUE TITLE
Bug: Cannot find module '@gtm-support/vue-gtm' or its corresponding type declarations

### ISSUE THREAD

**Issue by slauzinho** [gtm-support/vue-gtm#421]
## Info

| Tool   | Version       |
| ------ | ------------- |
| Plugin | v3.0.0        |
| Vue    | v3.4.27        |
| Node   | v18.18.2        |
| OS     | mac

## Output or Error

```bash
Cannot find module '@gtm-support/vue-gtm' or its corresponding type declarations.
```

## Expected Output
No ts errors

## Additional Context
- Version `2.2.0` worked as expected only version 3 is throwing the error

**Comment by Shinigami92** [comment]
Please test out v3.0.1 and if it does not work then reopen this issue

**Comment by vitaliitrush** [comment]
![CleanShot 2024-06-03 at 18 43 03@2x](https://github.com/gtm-support/vue-gtm/assets/144781590/ea2e29ab-e312-4fb4-939f-f732d9bf32ac)

Please make 'vue-router' as an external dependency

**Comment by Shinigami92** [comment]
> ![CleanShot 2024-06-03 at 18 43 03@2x](https://private-user-images.githubusercontent.com/144781590/336139319-ea2e29ab-e312-4fb4-939f-f732d9bf32ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0Mjk4NDcsIm5iZiI6MTcxNzQyOTU0NywicGF0aCI6Ii8xNDQ3ODE1OTAvMzM2MTM5MzE5LWVhMmUyOWFiLWUzMTItNGZiNC05MzlmLWY3MzJkOWJmMzJhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxNTQ1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmRiYWJlNWI3MDY4ZmJmNTQ0OWI1N2IxYzEzNTgyZjlhMjhiMjQ3MjNlYmJkNjdkMzQwNjc1OTJjYjI5OTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2uQUP5RgZmsc0N7jvJd-pHkngnhBFyl8cFIifOX_5_I)
> 
> Please make 'vue-router' as an external dependency

Is this an issue with tsup? https://tsup.egoist.dev/#excluding-packages

Maybe also open a separate issue for that
Also please try to create a PR for that. Checkout the repo and run the build command, then see that this is only in `.d.ts` file
I'm not sure how to fix this right now

**Comment by slauzinho** [comment]
@Shinigami92 Version `3.0.1` fixes the issue, thank you 👍

**Comment by vitaliitrush** [comment]
@slauzinho  how did you handle VueRouter error?

**Comment by slauzinho** [comment]
I don't have that error, maybe because I'm using vue-router?

**Comment by vitaliitrush** [comment]
I'm using vue-router too))

**Comment by vitaliitrush** [comment]
![CleanShot 2024-06-03 at 19 11 17](https://github.com/gtm-support/vue-gtm/assets/144781590/16cfc707-394c-48a9-9b9a-eb71e0f4854e)

**Comment by vitaliitrush** [comment]
@Shinigami92 external did not help :(

**Comment by slauzinho** [comment]
I get not warnings / errors doing this:

```ts
app.use(
  createGtm({
    id: 'GTM-W3DQ5CH',
    queryParams: {
      gtm_auth: import.meta.env.VITE_GTM_AUTH,
      gtm_preview: import.meta.env.VITE_GTM_PREVIEW,
      gtm_cookies_win: 'x',
    },
    enabled: !import.meta.env.DEV,
    loadScript: !import.meta.env.DEV,
    vueRouter: router,
  })
);
```

Using:
```
"vue-router": "^4.3.2",
"vue": "^3.4.27",
"@gtm-support/vue-gtm": "^3.0.1",
"typescript": "^5.4.5",
```

**Comment by vitaliitrush** [comment]
fixed lol
![CleanShot 2024-06-14 at 15 09 24](https://github.com/gtm-support/vue-gtm/assets/144781590/211c527f-83e9-4aae-9edb-0cff2375f700)
