### ISSUE TITLE
The GTM is sending the previous document title

### ISSUE THREAD

**Issue by Glideh** [gtm-support/vue-gtm#447]
## Info

| Tool   | Version       |
| ------ | ------------- |
| Plugin | v3.0.1        |
| Vue    | v3.3.11        |
| Node   | v20.9.0        |
| OS     | Dockerized Alpine |

## Input

Before this JS, the document title is `Previous product`

```js
const page_title = 'Current product'
document.title = page_title
gtm.trackView(route.name.toString() + route.path, { page_title })
```

## Output or Error

I'm getting the page view with the `Previous product` page title

## Expected Output

Get the `Current product` page title

## Additional Context

Here I'm getting some product data asynchronously from an API then appending it on the document title before firing the `trackView`.
Also, I'm actually using the `vueRouter` option just excluding this route to fire it manually.

```js
app.use(createGtm({
    id: gtmId,
    vueRouter: router,
    ignoredViews: ['product'],
}))
```

**Comment by Shinigami92** [comment]
Could you try enabling the `trackOnNextTick` option?

**Comment by Glideh** [comment]
Yes I tried that too, didn't seem to have any effect

**Comment by Shinigami92** [comment]
You have several possibilities now:

- modify your local node_modules content and e.g. use console.log statements
- link a clone of vue-gtm / core to your project and debug that way
- provide a minimal reproducible (github repo) that can be checked out to test and debug
- write a test in this or core repo to identify the wanted behavior

**Comment by Glideh** [comment]
Thanks for your suggestions I'll try that

**Comment by Glideh** [comment]
Turned out we misread the events in the console... It's actually working fine.
Thanks again for your help, sorry for the false alarm
