### ISSUE TITLE
1.2 vue3 dont work without vue-router

### ISSUE THREAD

**Issue by aldarund** [gtm-support/vue-gtm#79]
version 1.1 works without having vue-router as dep in project.
Version 1.2 dont work anymore without vue-router

```
vue-tsc --noEmit && vite build

node_modules/.pnpm/registry.npmjs.org+@gtm-support+vue-gtm@1.2.0_vue@3.2.12/node_modules/@gtm-support/vue-gtm/dist/index.d.ts:4:54 - error TS2307: Cannot find module 'vue-router' or its corresponding type declarations.

4 import type { RouteLocationNormalized, Router } from 'vue-router';
```

**Comment by Shinigami92** [comment]
Oh thanks for the info :slightly_smiling_face: 

Could you please tell me with package manager you are using?
Cause I changed to a more modern `package.json` syntax using `peerDependenciesMeta`.

https://github.com/gtm-support/vue-gtm/commit/ed55414e97563d49c93435a09943f4ec296267cd#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R84-R88

So could be you may need to update to npm 7+ or yarn v2+ :thinking: 
Could you try that out for me?

**Comment by aldarund** [comment]
Happens on both latest pnpm and on yarn 1.x

**Comment by Shinigami92** [comment]
Mh, at least `pnpm` `6.x` should support it: https://pnpm.io/package_json#peerdependenciesmeta :thinking:  

`yarn v1` doesn't support it.

I will look into it tomorrow... It's late here :sleeping:

**Comment by aldarund** [comment]
npm 7.x also same problem. Didnt checked yarn 2.x but shoudnt matter if its not working anywhere else

>I will look into it tomorrow... It's late here 😴

No hurry at all, always possible to use 1.1 version till its fixed  ;)

**Comment by Shinigami92** [comment]
Could you please test `1.2.1`?

**Comment by aldarund** [comment]
1.2.1 - still same error for npm 7 and pnpm, didnt tested with yarn.

**Comment by Shinigami92** [comment]
`1.2.2` ... sorry 😅

**Comment by aldarund** [comment]
1.2.2 works fine
