### ISSUE TITLE
gtm_auth - where to get this?

### ISSUE THREAD

**Issue by christodupreez** [gtm-support/vue-gtm#8]
Do I need to replace the gtm_auth: 'AB7cDEf3GHIjkl-MnOP8qr'?

If so, where do I get this?

**Comment by Shinigami92** [comment]
I don't know if it's required. The whole `queryParams` object is optional.
Sadly I also don't find something useful about it. And it was already there when I took over the project 🤔

**Comment by glen-84** [comment]
When you create additional environments in GTM, these 3 query parameters are added to the snippet.

If you're just using the default environment (`Live`, I assume), then you don't need to set these values. If you still want to specify them for whatever reason, then you should be able to find the values in the `Environments` section (in the provided snippets).

**Comment by Shinigami92** [comment]
@glen-84 Good to know.
If you want, please open a PR an add your comment as documentation to e.g. the `README.md`

Please only use the `main` branch for this. I will keep track of the extra `vue2-gtm` branch by myself.
