### ISSUE TITLE
Bug: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by ebisbe** [gtm-support/vue-gtm#96]
## Info

| Tool   | Version       |
| ------ | ------------- |
| Plugin | v1.2.2        |
| Vue    | 3.2.20        |
| Node   | v17.0.1        |
| OS     | mac |

## Input

```js

```

## Output or Error

```bash

```

## Expected Output

```bash

```

## Additional Context

When building the project with vite-ssg you are prerendering every page. There's no document so it crashes when building it for every page.

It's the same issue it happened https://github.com/henk-badenhorst/vue-hotjar-next/issues/11 and the same solution should work. 

Add `if (typeof window === 'undefined') return` previous to line to avoid calling the `loadScript()` function.

**Comment by Shinigami92** [comment]
Please open a PR with the change and potentially a working test that does fail when the fix is not applied.

**Comment by Shinigami92** [comment]
Are you sure that https://github.com/gtm-support/core/blob/687524ae88b6efa11644181f6709799dce713726/src/gtm-support.ts#L94 is not already sufficient enough?
Do you also have any example of an error that you get?

**Comment by ebisbe** [comment]
@Shinigami92 here you can try it https://github.com/Skedr/landing/tree/gtm install with `npm` and then run `npm run build`

**Comment by ebisbe** [comment]
Updating this line https://github.com/gtm-support/core/blob/33ed2424c61665129e2bf3d3daf0d708ef5b9050/src/gtm-support.ts#L69 should do the trick as you said. 

Checking window and document

**Comment by Shinigami92** [comment]
Oh wait, now I'm bit confused 🤔 
This line is there so that the plugin doesn't run when `window` is not defined.
But in you example from above (`if (typeof window === 'undefined') return previous`) what is `previous`?

Like I said, I will now await just a PR from you, and then it is easier to discuss in the PR. Cause I don't want to waste time with something to find out when you already know exactly what you want 🙂 
I hope you can understand.

**Comment by ebisbe** [comment]
Ops, I copy pasted and set the ticks \` in the wrong word.  Previous was meant to be explanation sentence. I've updated the upper comment. In your case,  as everything has been set up is check if neither `window` nor `document` exists. 
I reviewed your test for `isInBrowserContext()` but I'm not sure how would you want to test it.
